name: Test all modules
on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test-all:
    runs-on: ubuntu-latest 
    strategy:
      matrix: 
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v2 
      - name: Get Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2 
        with:
          python-version: ${{ matrix.python-version }} 
      - name: Get dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
          pip install -r test_requirements.txt
          sudo apt-get install -y xvfb
      - name: Run test with pytest
        run: |
          pytest -v
